# Generate Codecov report

name: Generate Codecov Reports
on:
  push:

jobs:
  release:
    name: Release to Github
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ip2location/ip2location-io-go
        verbose: true
